# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638af7437bf6d2f8a83b59822d3677bce37194bcb16ecfd5c171f890842770dc5f87c1646deae4116b93bada2baea6413775f4b405376790c874d716e88d60dc

test:
  secret_key_base: b56c8aae5b5f24852f0d7eef1dab8422532b1cf3817351e1b06a6c606e49af90ce3dd853df2d7366436be2b9b0577ad873dc9d6a570827a99dca37b19f22b7cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
